### ISSUE TITLE
Fixing OCR for Mentawai 1933 list

### ISSUE THREAD

**Issue by gederajeg** [complexico/holle-list-barrier-islands#1]
The fixing is being done in R and tracked [here](https://github.com/gederajeg/holle-list-barrier-islands/blob/main/ocr-mentawai-1933.R).

**Comment by engganolang** [comment]
Done; see the file [here](https://github.com/complexico/holle-list-barrier-islands/blob/main/plaintexts/mentawai1933.txt)
